
export const metadata = {
  title: 'Shipesa - Dashboard',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
    </body>
    </html>
  )
}
